namespace Contracts.Dtos.Errors
{
    public static class ErrorCodes
    {
        public const string REQUIRED_FIELD_IS_EMPTY = "REQUIRED_FIELD_IS_EMPTY";
        public const string UNAUTHORIZED_ACTION_FOR_CALLING_USER = "UNAUTHORIZED_ACTION_FOR_CALLING_USER";
        public const string APPLICATION_ERROR = "APPLICATION_ERROR";
        public const string ERROR_PROCESSING_SQL_ON_DB_SERVER = "ERROR_PROCESSING_SQL_ON_DB_SERVER";
        public const string ERROR_EXECUTING_SCAFFOLDING_COMMAND = "ERROR_EXECUTING_SCAFFOLDING_COMMAND";
        public const string ERROR_DROPPING_TEMPORARY_DATABASE = "ERROR_DROPPING_TEMPORARY_DATABASE";
        public const string ERROR_CREATING_NEW_TEMPORARY_DATABASE = "ERROR_CREATING_NEW_TEMPORARY_DATABASE";
        public const string ERROR_RUNNING_SCRIPT_ON_TEMPORARY_DATABASE = "ERROR_RUNNING_SCRIPT_ON_TEMPORARY_DATABASE";
        public const string ERROR_DATABASE_ENGINE_NOT_SUPPORTED = "ERROR_DATABASE_ENGINE_NOT_SUPPORTED";
    }
}
